spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/new_camo?characterEncoding=UTF-8&serverTimezone=UTC
    username: jcw
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

jwt:
  secretKey: NEW_CAMO_SECRET_KEY